version: '3.8'

services:
  geth-init:
    image: ethereum/client-go
    container_name: geth-init
    network_mode: "host"
    volumes:
      - /home/ethereum/execution/datadir:/datadir
      - /home/ethereum/execution/genesis.json:/genesis.json:ro
    command: ["init", "--datadir", "/datadir", "/genesis.json"]

  geth:
    depends_on:
      geth-init:
        condition: service_completed_successfully
    image: ethereum/client-go
    container_name: geth
    network_mode: "host"
    volumes:
      - /home/ethereum/jwtsecret:/jwtsecret:ro
      - /home/ethereum/execution/datadir:/datadir
      - /home/ethereum/execution/password.txt:/password.txt:ro
    command: [
      "--networkid", "3151908",
      "--http",
      "--http.api", "eth,net,web3,engine",
      "--authrpc.jwtsecret=/jwtsecret",
      "--datadir", "/datadir",
      "--password", "/password.txt"
    ]

  beacon:
    image: gcr.io/offchainlabs/prysm/beacon-chain:stable
    container_name: beacon
    network_mode: "host"
    environment:
      - BOOTSTRAP_IP=${BOOTSTRAP_IP}
      - NODE_ID=${NODE_ID}
    volumes:
      - /home/ethereum/consensus/datadir:/datadir
      - /home/ethereum/jwtsecret:/jwtsecret:ro
      - /home/ethereum/consensus/genesis.ssz:/genesis/genesis.ssz:ro
      - /home/ethereum/consensus/config.yml:/config/config.yml:ro
    command: [
      "--datadir=/datadir",
      "--genesis-state=/genesis/genesis.ssz",
      "--bootstrap-node", "/ip4/${BOOTSTRAP_IP}/udp/13000/quic-v1/p2p/${NODE_ID}",
      "--peer", "/ip4/${BOOTSTRAP_IP}/udp/13000/quic-v1/p2p/${NODE_ID}",
      "--execution-endpoint=http://127.0.0.1:8551",
      "--jwt-secret=/jwtsecret",
      "--chain-config-file=/config/config.yml",
      "--min-sync-peers=1",
      "--accept-terms-of-use"
    ]
